server:
  port: 8080
---
api:
  host:
    baseurl: http://localhost:8080/api/v1
spring:
  application:
    name: qa-service
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    format:
      date: iso
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    prefix: file:src/main/resources/templates/
