---
name: gradle build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Build
    strategy:
      matrix:
        os: [windows-2022, macos-12]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: gradlew clean build --no-daemon --console=plain --max-workers=1 --build-cache --configure-on-demand --continue
